### ISSUE TITLE
How to setting file .env

### ISSUE THREAD

**Issue by tunguyenht** [mihailgaberov/bingo#24]
Dear Mihail Gaberov, 
can you guide me to install mongo file?
how to set value DB_SECRET?

DB_SECRET=4D-oSUS0SN74RC80Cfg4hdxamZqatYE39iaw9vUK18c
DB_URI=mongodb://192.168.58.111/bingo

Tks you

**Comment by mihailgaberov** [comment]
You just need to create a `.env` file in your root folder and add these values in it. Simple google search shows you different options depending on what OS or IDE are you using - https://www.google.com/search?q=how+to+create+a+env+file&rlz=1C1GCEU_enES947ES947&oq=how+to+create+a+env+file&aqs=chrome.0.0i512l5j0i22i30l5.2965j0j1&sourceid=chrome&ie=UTF-8

**Comment by tunguyenht** [comment]
Can not insert database? please help me 
![image](https://user-images.githubusercontent.com/25703973/136578638-77fbcd64-c7ce-4485-8863-ef7bdab82dd7.png)
![image](https://user-images.githubusercontent.com/25703973/136578692-ef6953f7-70be-4543-8818-32e1044034c5.png)

![image](https://user-images.githubusercontent.com/25703973/136578570-0cccc5cf-d8c5-4a36-a7f5-b8f324ac3c69.png)

**Comment by tunguyenht** [comment]
yes, getting the token successfully, but not login to admin and insert to database

**Comment by mihailgaberov** [comment]
Did you try to spin up the back-office and login?

**Comment by tunguyenht** [comment]
![image](https://user-images.githubusercontent.com/25703973/136579620-2c83e7bf-58a7-4351-9af9-20566603f701.png)
![image](https://user-images.githubusercontent.com/25703973/136579664-1113901e-2c2a-4bd5-b714-136088194f47.png)

you can teamview support me please help me :(

**Comment by tunguyenht** [comment]
I can not login user :( 
1. config databae
![image](https://user-images.githubusercontent.com/25703973/136584633-d5d98cea-0a25-49f0-89bd-210dc4ec6151.png)
2. config file .env
![image](https://user-images.githubusercontent.com/25703973/136584716-b20db69e-c2f0-4ee1-aaa3-0e459e8965d7.png)
3. index dabase
![image](https://user-images.githubusercontent.com/25703973/136584808-89ab62fd-dc43-4ba2-8ddd-46e074857af0.png)
4. login
![image](https://user-images.githubusercontent.com/25703973/136584846-8ae26b5d-21b1-424c-a863-ea37ef4bfe1d.png)
 :(

**Comment by tunguyenht** [comment]
Hi i send consolog login
![image](https://user-images.githubusercontent.com/25703973/136590217-528531ae-6918-40e9-baaa-447c868100e7.png)

**Comment by mihailgaberov** [comment]
Glad you figured it out. Cheers:)
