### ISSUE TITLE
error create admin user

### ISSUE THREAD

**Issue by edwinosky** [mihailgaberov/bingo#9]
I use the postman app to generate the POST request, it generates the token but it says error when I enter the data in the backoffice panel
![image](https://user-images.githubusercontent.com/26192834/85186116-c6302200-b25c-11ea-9483-ff7b1e161663.png)
![image](https://user-images.githubusercontent.com/26192834/85186127-d516d480-b25c-11ea-9937-7f18952a15aa.png)

**Comment by mihailgaberov** [comment]
Do you have a .env file with proper configurations?

**Comment by edwinosky** [comment]
yes i have the correct settings in .env i think it would give error when i run node server.js


![image](https://user-images.githubusercontent.com/26192834/85214434-ef6db280-b32f-11ea-8980-d4888454422e.png)

**Comment by mihailgaberov** [comment]
Can you make a screenshot of the console tab from chrome dev tools? What errors are you getting?

**Comment by edwinosky** [comment]
![image](https://user-images.githubusercontent.com/26192834/85229901-2edce300-b3b2-11ea-9275-da7e97d360a1.png)

**Comment by mihailgaberov** [comment]
Looks like you don't have a running server. Basically you need to have 3 things running, in order to have the full app functioning normally - the app itself, the server and the mongodb. You start the game via gulp and the server with Node.js (`node server.js`).

**Comment by edwinosky** [comment]
If exactly I have mongodb running, then I run node server.js, and lastly I run gulp

in fact I think that if this mongodb is not running, the node server.js would give an error, and it does not give me an error, DB connected tells me, that is, everything is fine, then I run gulp, I can register a normal user and I can enter, but I need is to add admin user.
I do all the steps indicated to create the admin, but it gives me an error when entering the credentials. it would be nice if you added a global admin user

Thanks for your help.

**Comment by mihailgaberov** [comment]
Give me a sec, I am setting up the project on a new PC, so I will do a fresh install and try.

**Comment by mihailgaberov** [comment]
Ok, I did it and it seems to be working fine. Could you show me how do you start MongoDB server? Also, can you use some database management software, such as MongoDB Compass, and inspect whether your have the correct records there.

What I just did is:
1. Checked out the project
2. Set my .env file
3. Installed gulp globally and locally
4. Installed MongoDB server
5. Created an empty dir in C:\data\db to store the DB records.
6. Ran the server via 'mongod' command in the /bin folder of the installation (C:\Program Files\MongoDB\Server\4.2\bin in my case).
7. Ran 'node server.js' in  the root dir of the poject
8. Ran 'gulp' in the root dir of the project
9. Created a new admin user via Insomnia (as described in the readme)
10. Opened http://localhost:8000/back-office.html and logged with the credentials from the previous step.

**Comment by edwinosky** [comment]
ready, i managed to solve it with mongodb compass, apparently the mongodb server had a problem in the configuration file, it had the option #auth=true activated, comment it and restart the daemon, and ready it worked, thanks for your time

Thanks to the graphic application I was able to realize that the users were not registering through the POST command to the api, and I could deduce that the problem was the mongo server and not your software

![image](https://user-images.githubusercontent.com/26192834/85232773-4c687780-b3c7-11ea-90f6-1dab1da1a27b.png)

**Comment by ansalo1021** [comment]
I solved the problem by adding the following line


![Captura](https://user-images.githubusercontent.com/88809335/130283144-af5f08f1-095b-4f7e-8909-b62c295da682.PNG)
